#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
from collections import Counter
from pathlib import Path
import subprocess
import sys
import zipfile

ROOT = Path(__file__).resolve().parents[1]
SKILL_NAME = "human-writing-ru"
FIXED_DT = (2020, 1, 1, 0, 0, 0)
EXCLUDE_NAMES = {"FILES.sha256", "PACKAGE_CONTENTS.md"}
CLEAN_DIR_NAMES = {"__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache"}
CLEAN_FILE_NAMES = {".coverage", ".DS_Store"}
PACKAGE_EXCLUDE_DIR_NAMES = CLEAN_DIR_NAMES | {
    ".git",
    ".agents",
    ".ai-factory",
    ".codex",
    ".opencode",
    ".venv",
    "node_modules",
}
PACKAGE_EXCLUDE_FILE_NAMES = CLEAN_FILE_NAMES | {".gitignore"}
PACKAGE_EXCLUDE_REL_DIRS: set[Path] = set()
PACKAGE_DATA_FILES = {
    Path("data/README.md"),
    Path("data/corpus_manifest.example.csv"),
}


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def clean_generated() -> None:
    # Remove local/runtime artifacts before computing manifests.
    for p in sorted(ROOT.rglob("*"), key=lambda x: len(x.parts), reverse=True):
        if p.is_file() and (p.suffix == ".pyc" or p.name in CLEAN_FILE_NAMES):
            p.unlink(missing_ok=True)
        elif p.is_dir() and p.name in CLEAN_DIR_NAMES:
            import shutil
            shutil.rmtree(p, ignore_errors=True)


def package_files(include_generated_manifests: bool = True) -> list[Path]:
    files=[]
    for p in ROOT.rglob("*"):
        if not p.is_file():
            continue
        rel=p.relative_to(ROOT)
        if any(part in PACKAGE_EXCLUDE_DIR_NAMES for part in rel.parts):
            continue
        if rel.parts and rel.parts[0] == "data" and rel not in PACKAGE_DATA_FILES:
            continue
        if any(rel == excluded or excluded in rel.parents for excluded in PACKAGE_EXCLUDE_REL_DIRS):
            continue
        if p.suffix == ".pyc" or p.name in PACKAGE_EXCLUDE_FILE_NAMES:
            continue
        if not include_generated_manifests and p.name in EXCLUDE_NAMES:
            continue
        files.append(p)
    return sorted(files, key=lambda x: x.relative_to(ROOT).as_posix())



def write_release_integrity() -> None:
    version=(ROOT/"VERSION").read_text(encoding="utf-8").strip()
    tracked=[
        "SKILL.md",
        "profiles/editorial-baseline.json",
        "scripts/check_prose_ru.py",
        "scripts/ablate_signals.py",
        "benchmark/ablation/spec-v3.json",
        "scripts/ablate_signals_v3.py",
        "scripts/validate_external_heldout.py",
        "scripts/run_external_heldout_gate.py",
        "benchmark/external-heldout/SOURCE_REGISTRY.json",
        "benchmark/external-heldout/SOURCE_MANIFEST.csv",
        "scripts/check_edit_integrity.py",
        "scripts/check_tz_ru.py",
        "profiles/tz-rules.ru.json",
        "profiles/tz-profiles.json",
        "references/technical-specification.md",
        "evals/tz_rule_cases.json",
        "quality/TZ_REALWORLD_REGRESSION.json",
        "TZ_NORMALIZATION.md",
        "references/ai-writing-patterns.md",
        "evals/humanizer_adaptation_cases.json",
        "THIRD_PARTY_NOTICES.md",
        "scripts/prepare_ab_eval.py",
        "scripts/aggregate_ab_eval.py",
    ]
    frozen=json.loads((ROOT/"benchmark/external-heldout/FROZEN_INPUT_SHA256.json").read_text(encoding="utf-8"))["sha256"]
    actual_frozen={rel:sha256(ROOT/rel) for rel in frozen}
    report={
        "schema_version":1,
        "package_version":version,
        "policy_version":"1.4.0",
        "skill_root":SKILL_NAME,
        "frozen_inputs_match":all(actual_frozen[rel]==expected for rel,expected in frozen.items()),
        "frozen_expected":frozen,
        "frozen_actual":actual_frozen,
        "tracked_sha256":{rel:sha256(ROOT/rel) for rel in tracked},
        "note":"Current-package integrity snapshot generated by scripts/build_release.py; historical benchmark integrity snapshots keep their original release field and are not current-tree manifests.",
    }
    path=ROOT/"quality/RELEASE_INTEGRITY.json"
    path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")

def write_hash_manifest() -> None:
    lines=[]
    for p in package_files(include_generated_manifests=False):
        rel=p.relative_to(ROOT).as_posix()
        lines.append(f"{sha256(p)}  {rel}")
    (ROOT/"FILES.sha256").write_text("\n".join(lines)+"\n",encoding="utf-8")


def write_inventory() -> None:
    version=(ROOT/"VERSION").read_text(encoding="utf-8").strip()
    files=package_files(include_generated_manifests=True)
    counts=Counter((p.relative_to(ROOT).parts[0] if len(p.relative_to(ROOT).parts)>1 else "(root)") for p in files)
    lines=[
        "# Package contents", "",
        f"Complete installable package for `{SKILL_NAME}`, version **{version}**.", "",
        "The ZIP root is the stable Agent Skills directory `human-writing-ru/`; the version belongs to the archive name and metadata, not to the install directory.", "",
        "## Inventory", "",
    ]
    for k in sorted(counts): lines.append(f"- `{k}`: {counts[k]} files")
    lines += ["", f"Total files: **{len(files)}**.", "", "## Integrity", "", "`FILES.sha256` hashes every packaged file except `FILES.sha256` and `PACKAGE_CONTENTS.md` itself to avoid self-reference.", "", "Build with:", "", "```bash", "python3 scripts/build_release.py --output-dir /path/to/output", "```", ""]
    (ROOT/"PACKAGE_CONTENTS.md").write_text("\n".join(lines),encoding="utf-8")


def validate() -> None:
    env={**__import__('os').environ,'PYTHONDONTWRITEBYTECODE':'1'}
    p=subprocess.run([sys.executable,str(ROOT/'scripts/validate_skill.py')],cwd=ROOT,env=env,text=True,capture_output=True)
    if p.returncode:
        raise SystemExit("validate_skill failed before packaging:\n"+p.stdout+p.stderr)


def write_zip(out: Path) -> None:
    out.parent.mkdir(parents=True,exist_ok=True)
    with zipfile.ZipFile(out,"w",compression=zipfile.ZIP_DEFLATED,compresslevel=9) as zf:
        for p in package_files(include_generated_manifests=True):
            rel=p.relative_to(ROOT).as_posix()
            zi=zipfile.ZipInfo(f"{SKILL_NAME}/{rel}",FIXED_DT)
            zi.compress_type=zipfile.ZIP_DEFLATED
            zi.external_attr=(0o755 if p.suffix==".py" and p.parent.name in {"scripts","tests"} else 0o644) << 16
            zf.writestr(zi,p.read_bytes(),compress_type=zipfile.ZIP_DEFLATED,compresslevel=9)


def main() -> int:
    ap=argparse.ArgumentParser(description="Build deterministic installable human-writing-ru release")
    ap.add_argument("--output-dir",type=Path,required=True)
    args=ap.parse_args()
    if ROOT.name != SKILL_NAME:
        raise SystemExit(f"skill directory must be named {SKILL_NAME!r}, got {ROOT.name!r}")
    clean_generated()
    write_release_integrity()
    write_hash_manifest()
    write_inventory()
    validate()
    version=(ROOT/"VERSION").read_text(encoding="utf-8").strip()
    out=args.output_dir/f"{SKILL_NAME}-{version}-full.zip"
    write_zip(out)
    digest=sha256(out)
    sha_path=args.output_dir/f"{out.name}.sha256.txt"
    sha_path.write_text(f"{digest}  {out.name}\n",encoding="utf-8")
    print(f"zip={out}")
    print(f"sha256={digest}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
